# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options


class TestActivityModuleUser():
    def setup_method(self, method):
        # Crear objeto de opciones de Chrome
        options = Options()
        # Desactivar GPU
        options.add_argument("--disable-gpu")
        # Ejecutar en modo headless (sin interfaz gráfica)
        options.add_argument("--headless")
        # # Inicializar el driver con las opciones configuradas
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_activity_user(self):
        self.driver.get("http://localhost:5173/")
        self.driver.set_window_size(1552, 832)
        wait = WebDriverWait(self.driver, 10)
        # Logearse con usuario de prueba
        self.driver.find_element(By.XPATH, "//input[@id=\':r1:\']").click()
        self.driver.find_element(By.NAME, "email").send_keys(
            "karlo.romero@unmsm.edu.pe")
        self.driver.find_element(By.XPATH, "//input[@id=\':r3:\']").click()
        self.driver.find_element(By.NAME, "password").send_keys("root")
        self.driver.find_element(
            By.XPATH, "//button[@type=\'submit\']").click()
        time.sleep(3)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Mis actividades publicadas\')])[2]").click()
        # Crear actividad válida con datos válidos
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[5]").click()
        self.driver.find_element(
            By.NAME, "title").send_keys("Taller Prueba 01")
        self.driver.find_element(
            By.XPATH, "//div[@id=\'mui-component-select-eventType\']").click()
        self.driver.find_element(By.XPATH, "//body").click()
        self.driver.find_element(
            By.XPATH, "//li[contains(.,\'Taller\')]").click()
        self.driver.find_element(By.XPATH, "//textarea[@id=\':rh:\']").click()
        self.driver.find_element(
            By.NAME, "description").send_keys("Aprender Python")
        self.driver.find_element(By.XPATH, "//input[@id=\':rj:\']").click()
        date_input = self.driver.find_element(
            By.NAME, "startDate")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(By.XPATH, "//input[@id=\':rl:\']").click()
        date_input = self.driver.find_element(
            By.NAME, "endDate")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("05")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(By.XPATH, "//input[@id=\':rn:\']").click()
        self.driver.find_element(By.NAME, "location").send_keys("Lima")
        self.driver.find_element(
            By.XPATH, "//button[@type=\'submit\']").click()
        time.sleep(3)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Ver actividades\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Mis actividades publicadas\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/aside/div/div/div/div[2]/div[2]/div/input").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/aside/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[8]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/h6")
        # Crear actividad con datos incompletos
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[5]").click()
        self.driver.find_element(
            By.XPATH, "//button[@type=\'submit\']").click()
        time.sleep(3)
        assert self.driver.find_element(
            By.XPATH, "//p[contains(.,\'Se aceptan inscripciones\')]").text == "Se aceptan inscripciones"
        self.driver.find_element(By.NAME, "location").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".MuiButton-outlined").click()
        # Editar actividad con datos válidos
        self.driver.find_element(
            By.XPATH, "/html/body/div[4]/div[3]/div/div/form/div[6]/button[1]").click()
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[11]").click()
        self.driver.find_element(By.NAME, "title").click()
        self.driver.find_element(By.NAME, "title").clear()
        self.driver.find_element(By.NAME, "title").click()
        self.driver.find_element(By.NAME, "title").send_keys(
            "02")
        self.driver.find_element(
            By.XPATH, "//button[@type=\'submit\']").click()
        time.sleep(3)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Ver actividades\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[6]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "//*[@id='root']/div/div/main/div/div/div/div/div[2]/h6")
        # Ver lista de actividades publicadas / Ver actividades con filtro válido
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Mis actividades publicadas\')])[2]").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/aside/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[8]").click()
        time.sleep(2)
        assert self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div/div/div[2]/p/strong").text == "Descripción:"
        # Registrase en una actividad
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Ver actividades\')])[2]").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[6]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[8]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "//button[@type=\'submit\']").click()
        time.sleep(3)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Actividades registradas\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[7]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div[2]/div/div[2]/h6")
        # Visualizar lista de participantes
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Mis actividades publicadas\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/aside/div/div/div/div[2]/div[2]/div/input").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/aside/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "//*[@id='root']/div/div/aside/div/div/div/div[2]/button[1]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "//*[@id='root']/div/div/main/div/div/div/div/div[1]/div[3]/div/button[1]").click()
        time.sleep(3)
        assert self.driver.find_element(
            By.XPATH, "//td[contains(.,\'19200101\')]").text == "19200101"
        # Cancelar inscripción en una actividad
        self.driver.find_element(
            By.CSS_SELECTOR, ".MuiButton-outlined").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Actividades registradas\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[7]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[9]").click()
        self.driver.find_element(
            By.XPATH, "//button[@type=\'submit\']").click()
        time.sleep(3)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Ver actividades\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/main/div/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[6]").click()
        time.sleep(2)
        elements = self.driver.find_elements(
            By.XPATH, "(//button[@type=\'button\'])[8]")
        assert len(elements) > 0
        # Eliminar actividad existente
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/header/div/div/div[3]/button/img").click()
        self.driver.find_element(
            By.XPATH, "(//a[contains(text(),\'Mis actividades publicadas\')])[2]").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/aside/div/div/div/div[2]/div[2]/div/input").click()
        date_input = self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/aside/div/div/div/div[2]/div[2]/div/input")
        date_input.click()  # Asegúrate de que el campo esté enfocado
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys(Keys.ARROW_LEFT)
        date_input.send_keys("01")  # Día
        date_input.send_keys(Keys.ARROW_RIGHT)
        date_input.send_keys("12")  # Mes
        date_input.send_keys(Keys.ARROW_LEFT)  # Mover al siguiente campo
        date_input.send_keys("002026")  # Año
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[8]").click()
        time.sleep(2)
        self.driver.find_element(
            By.XPATH, "(//button[@type=\'button\'])[12]").click()
        self.driver.find_element(
            By.XPATH, "//button[@type=\'submit\']").click()
        time.sleep(3)
        self.driver.find_element(
            By.XPATH, "//div[@id=\'root\']/div/div/div/div/div[2]/p").click()
        assert self.driver.find_element(
            By.CSS_SELECTOR, ".text-sm").text == "Actividad eliminada con éxito."
        # Cerrar sesión
        self.driver.find_element(
            By.CSS_SELECTOR, ".MuiButtonBase-root > .MuiAvatar-root > img").click()
        self.driver.find_element(
            By.XPATH, "//div[@id=\'menu-appbar\']/div[3]/ul/li[3]").click()
        self.driver.close()
